const disposableDomains = new Set([
  // 10minutemail & temp mail services
  '10minutemail.com', '10minutemail.net', '10minutemail.org', '10minutemail.xyz',
  '10minut.xyz', '10minutesmail.com', '10minmail.com', '10minute-mail.com',
  '10minutenmail.de', '10-minuten-mail.de',
  'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator.xyz',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'grr.la',
  'temp-mail.org', 'temp-mail.net', 'temp-mail.com', 'temp-mail.xyz',
  'tempmail.com', 'tempmail.net', 'tempmail.org', 'tempmail.xyz',
  'throwaway.email', 'throwawaymail.com', 'throwawaymail.xyz',
  'yopmail.com', 'yopmail.net', 'yopmail.org', 'yopmail.fr',
  'sharklasers.com', 'mailcatch.com', 'spam4.me',
  'mailexpire.com', 'mailexpire.net',
  'emailondeck.com', 'emailondeck.net',
  'getairmail.com', 'getairmail.net',
  'mail-temp.com', 'mailetc.com',
  'spambox.us', 'spambox.info', 'spambox.xyz',
  'tempinbox.com', 'tempinbox.net',
  'mailnator.com', 'mailnator.net',
  'maileater.com', 'maileater.net',
  'fakeinbox.com', 'fakeinbox.net', 'fakeinbox.org',
  'throwaway.email', 'throwaway.xyz',
  'maildrop.cc', 'maildrop.net', 'maildrop.org',
  'trashmail.com', 'trashmail.net', 'trashmail.org', 'trashmail.xyz',
  'trashmail.ws', 'trashmail.me',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',

  // Disposable mail services
  'disposable.com', 'disposable.net', 'disposable.org',
  'dispostable.com', 'dispostable.net',
  'mytemp.email', 'mytemp-mail.com', 'temp-mail.org',
  'generator.email', 'generatormail.com',
  'getnada.com', 'nada.email', 'nada.net',
  'hmail.org', 'hmail.net',
  'moakt.com', 'moakt.net', 'moakt.org',
  'incognitomail.com', 'incognitomail.net',
  'kurzepost.de', 'kurzepost.net',
  'mintemail.com', 'mintemail.net',
  'mytrashmail.com', 'mytrashmail.net',
  'temporarymail.org', 'temporarymail.net',
  'temporarily.de', 'temporarily.net',
  'tmpmail.net', 'tmpmail.org', 'tmpmail.xyz',
  'tmpeml.com', 'tmpeml.net',
  'tmpemails.com', 'tmpemails.net',
  'zippymail.com', 'zippymail.net', 'zippymail.info',
  'jetable.com', 'jetable.net', 'jetable.org',
  'mailsac.com', 'mailsac.net',
  'mailexpire.com', 'mailexpire.net',
  'quickinbox.com', 'quickinbox.net',
  'filzmail.com', 'filzmail.net',

  // Common spam domains
  'spamgoog.com', 'spamgoog.net',
  'spamthis.co.uk', 'spamthis.net',
  'spammotel.com', 'spammotel.net',
  'spamfree24.org', 'spamfree24.net',
  'spamsalad.com', 'spamsalad.net',
  'spamcero.com', 'spamcero.net',
  'spamdecoy.net', 'spamdecoy.org',
  'spamenuf.com', 'spamenuf.net',

  // One-click/temp registration services
  'mailmetrash.com', 'mailmetrash.net',
  'thanksnospam.com', 'thanksnospam.net',
  'nospamthanks.com', 'nospamthanks.net',
  'mt2009.com', 'mt2009.net',
  'mt2014.com', 'mt2014.net',
  'mt2015.com', 'mt2015.net',
  'frapmail.com', 'frapmail.net',
  'bongobongo.net', 'bongobongo.com',
  'bobmail.info', 'bobmail.net',
  'boun.cr', 'bouncr.com',
  'bx9.info', 'bx9.net',
  'chacuo.net', 'chacuo.org',
  'cool.fr.nf', 'cool.fr.net',
  'correo.blogos.net',
  'courriel.fr.nf',
  'cubiclink.com', 'cubiclink.net',
  'dicksinhisan.us', 'dicksinmyan.us',
  'dildosfromspace.com',
  'dodgeit.com', 'dodgeit.net',
  'dodgit.com', 'dodgit.net', 'dodgit.org',
  'donemail.ru', 'donemail.net',
  'dump-email.info', 'dump-email.net',
  'emailfake.com', 'emailfake.net', 'emailfake.ml',
  'emailias.com', 'emailias.net',
  'emailigo.de', 'emailigo.net',
  'emailiserver.de', 'emailiserver.net',
  'emaillime.com', 'emaillime.net',
  'emailsip.com', 'emailsip.net',
  'emailtemporanea.com', 'emailtemporanea.net',
  'emailtemps.com', 'emailtemps.net',
  'emlhub.com', 'emlhub.net',
  'emlpro.com', 'emlpro.net',
  'emltmp.com', 'emltmp.net',
  'fettemama.org', 'fettemama.net',
  'freeml.net', 'freeml.org',
  'gifto12.com', 'gifto12.net',
  'gowhit.com', 'gowhit.net',
  'haltospam.com', 'haltospam.net',
  'idnapp.com', 'idnapp.net',
  'inboxalias.com', 'inboxalias.net',
  'inboxbear.com', 'inboxbear.net',
  'inboxclean.com', 'inboxclean.net',
  'inboxclean.org',
  'inboxhub.net', 'inboxhub.org',
  'inboxstore.me', 'inboxstore.net',
  'ipnapp.com', 'ipnapp.net',
  'isdaq.com', 'isdaq.net',
  'karbasi.com.au',
  'kulturbetrieb.info',
  'lags.us', 'lags.net',
  'mail-temp.com', 'mail-temp.net',
  'mail1a.de', 'mail1a.net',
  'mail2rss.org', 'mail2rss.net',
  'mail4trash.com', 'mail4trash.net',
  'mailbidon.com', 'mailbidon.net',
  'mailbiz.biz',
  'mailblocks.com', 'mailblocks.net',
  'mailcat.biz',
  'mailchop.com', 'mailchop.net',
  'mailde.de', 'mailde.net',
  'maildrop.cc', 'maildrop.net',
  'maileater.com', 'maileater.net',
  'maileme101.com', 'maileme101.net',
  'mailexpire.com', 'mailexpire.net',
  'mailfa.tk', 'mailfa.xyz',
  'mailfreeonline.com', 'mailfreeonline.net',
  'mailhaven.com', 'mailhaven.net',
  'mailhood.com', 'mailhood.net',
  'mailimate.com', 'mailimate.net',
  'mailin8r.com', 'mailin8r.net',
  'mailismagic.com', 'mailismagic.net',
  'mailme.lv', 'mailme.xyz',
  'mailmetrash.com', 'mailmetrash.net',
  'mailmoat.com', 'mailmoat.net',
  'mailnator.com', 'mailnator.net',
  'mailnull.com', 'mailnull.net',
  'mailpick.biz',
  'mailpooch.com', 'mailpooch.net',
  'mailquack.com', 'mailquack.net',
  'mailscrap.com', 'mailscrap.net',
  'mailshiv.com', 'mailshiv.net',
  'mailslapping.com', 'mailslapping.net',
  'mailslite.com', 'mailslite.net',
  'mailsor.com', 'mailsor.net',
  'mailtothis.com', 'mailtothis.net',
  'mailtrash.net', 'mailtrash.org',
  'mymail-in.net', 'mymail-in.org',
  'mymailoasis.com', 'mymailoasis.net',
  'mytrashmail.com', 'mytrashmail.net',
  'netmails.com', 'netmails.net',
  'neverbox.com', 'neverbox.net',
  'nospam4.us', 'nospam4.net',
  'nowmymail.com', 'nowmymail.net',
  'oneoffemail.com', 'oneoffemail.net',
  'oopi.org', 'oopi.net',
  'pookmail.com', 'pookmail.net',
  'proxymail.eu', 'proxymail.net',
  'quickinbox.com', 'quickinbox.net',
  'rcpt.at', 'rcpt.net',
  'receiveee.com', 'receiveee.net',
  'regbypass.com', 'regbypass.net',
  'regbypass.com',
  'ringtone.com',
  'safetymail.info', 'safetymail.net',
  'sale.craigslist.org',
  'sayhi.net', 'sayhi.org',
  'selfdestructingmail.com', 'selfdestructingmail.net',
  'selfdestructmail.com', 'selfdestructmail.net',
  'sendspamhere.com', 'sendspamhere.net',
  'sharpmail.co.uk',
  'shortmail.net', 'shortmail.org',
  'sneakemail.com', 'sneakemail.net',
  'sofort-mail.de', 'sofort-mail.net',
  'spam.la', 'spam.net',
  'spam.su', 'spam.su',
  'spamavert.com', 'spamavert.net',
  'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.net', 'spambog.org',
  'spambox.info', 'spambox.net', 'spambox.org',
  'spamcannon.com', 'spamcannon.net',
  'spamcannon.com',
  'spamday.com', 'spamday.net',
  'spamex.com', 'spamex.net',
  'spamfree24.com', 'spamfree24.net', 'spamfree24.org',
  'spamgoog.com', 'spamgoog.net',
  'spamgourmet.com', 'spamgourmet.net',
  'spamhereplease.com', 'spamhereplease.net',
  'spamhole.com', 'spamhole.net',
  'spamify.com', 'spamify.net',
  'spaminator.de', 'spaminator.net',
  'spamkill.info', 'spamkill.net',
  'spaml.com', 'spaml.net',
  'spamlot.net', 'spamlot.org',
  'spammotel.com', 'spammotel.net',
  'spamobox.com', 'spamobox.net',
  'spamoff.xyz', 'spamoff.net',
  'spamsalad.com', 'spamsalad.net',
  'spamserver.info', 'spamserver.net',
  'spamslicer.com', 'spamslicer.net',
  'spamspame.com', 'spamspame.net',
  'spamspot.com', 'spamspot.net',
  'spamstack.net', 'spamstack.org',
  'spamthis.co.uk', 'spamthis.net',
  'spamworld.org', 'spamworld.net',
  'speed.1s.fr',
  'spoofmail.de', 'spoofmail.net',
  'superrito.com', 'superrito.net',
  'talkinator.com', 'talkinator.net',
  'teewars.org', 'teewars.net',
  'teleosaurs.xyz',
  'temp.emails', 'temp.emails.net',
  'tempail.com', 'tempail.net',
  'tempemail.biz', 'tempemail.net',
  'tempmail.us', 'tempmail.xyz',
  'tempmailer.com', 'tempmailer.net',
  'tempomail.fr', 'tempomail.net',
  'temporarily.de',
  'temporaryforwarding.com', 'temporaryforwarding.net',
  'temporaryinbox.com', 'temporaryinbox.net',
  'thankyou2010.com', 'thankyou2010.net',
  'thc.st', 'thc.st',
  'thisisnotmyrealemail.com', 'thisisnotmyrealemail.net',
  'throwaway.email', 'throwaway.net',
  'trash2009.com', 'trash2009.net',
  'trash-2009.com', 'trash-2009.net',
  'trash-2010.com', 'trash-2010.net',
  'trash-2011.com', 'trash-2011.net',
  'trash-2012.com', 'trash-2012.net',
  'trash-2013.com', 'trash-2013.net',
  'trash-2014.com', 'trash-2014.net',
  'trash-2015.com', 'trash-2015.net',
  'trash-2016.com', 'trash-2016.net',
  'trash-2017.com', 'trash-2017.net',
  'trash2010.com', 'trash2010.net',
  'trash2011.com', 'trash2011.net',
  'trash2012.com', 'trash2012.net',
  'trash2013.com', 'trash2013.net',
  'trash2014.com', 'trash2014.net',
  'trash2015.com', 'trash2015.net',
  'trash2016.com', 'trash2016.net',
  'trash2017.com', 'trash2017.net',
  'trashdevil.com', 'trashdevil.net',
  'trashymail.com', 'trashymail.net',
  'trashymail.org',
  'tyldd.com', 'tyldd.net',
  'uggsrock.com', 'uggsrock.net',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'wh4f.org', 'wh4f.net',
  'whyspam.me', 'whyspam.net',
  'willselfdestruct.com', 'willselfdestruct.net',
  'winemaven.info',
  'wronghead.com', 'wronghead.net',
  'wuzup.net', 'wuzup.org',
  'xagloo.com', 'xagloo.net',
  'xemaps.com', 'xemaps.net',
  'xents.com', 'xents.net',
  'xmaily.com', 'xmaily.net',
  'xoxy.net', 'xoxy.org',
  'yep.it', 'yep.net',
  'yogamaven.com',
  'yopmail.fr', 'yopmail.net',
  'yuurok.com', 'yuurok.net',
  'zehnminutenmail.de', 'zehnminutenmail.net',
  'zep-hyr.com', 'zep-hyr.net',
  'zippymail.info', 'zippymail.net',
  'zoaxe.com', 'zoaxe.net',
  'zoemail.org', 'zoemail.net',
  'zzz.com', 'zzz.net',
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;
  return disposableDomains.has(domain);
}

export function isValidEmail(email: string): boolean {
  if (!email || typeof email !== 'string') return false;
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) return false;
  return true;
}
